-- Tables for a fresh database.
-- Then run canvas-bounds.sql, getpixels.sql, placepixels.sql and rls.sql.
-- Existing single-canvas databases use migrations/001-multi-canvas.sql instead.
begin;

create type public.canvas_state as enum (
  'playable', -- visible and playable
  'readonly', -- visible but not playable
  'hidden'    -- neither visible nor playable
);

create table public.canvas (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  -- /canvas loads the most recent active canvas that isn't hidden
  -- (else the most recent visible one)
  active boolean not null default true,
  width integer not null default 100,
  height integer not null default 100,
  state public.canvas_state not null default 'playable',
  -- shown in the canvas selector
  name text not null,
  constraint canvas_pkey primary key (id),
  -- get_pixels_matrix sends every cell: bigger boards load too slowly
  constraint canvas_size_check check (width between 1 and 500 and height between 1 and 500),
  constraint canvas_name_check check (
    -- at least one visible character: \s misses NBSP and the zero-width spaces
    name ~ '[^\s\u00a0\u1680\u180e\u2000-\u200f\u2028-\u202f\u205f-\u2064\u3000\ufeff]'
    and char_length(name) <= 50
  )
) tablespace pg_default;

create table public.pixel (
  id uuid not null default gen_random_uuid(),
  created_at timestamp with time zone not null default now(),
  color text not null default '#000000'::text,
  -- 0 <= x < canvas.width and 0 <= y < canvas.height (see canvas-bounds.sql)
  x integer not null,
  y integer not null,
  canvas_id bigint not null,
  constraint pixel_pkey primary key (id),
  constraint pixel_canvas_id_fkey foreign key (canvas_id) references public.canvas (id) on delete cascade,
  constraint pixel_canvas_x_y_unique unique (canvas_id, x, y),
  constraint pixel_x_y_non_negative check (x >= 0 and y >= 0),
  constraint pixel_color_length_check check (char_length(color) <= 20)
) tablespace pg_default;

-- Lets Realtime match DELETEs on canvas_id and send the whole deleted row when
-- RLS is off. With rls.sql, DELETE payloads only carry the id (see README).
alter table public.pixel replica identity full;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
    and not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'pixel'
    )
  then
    alter publication supabase_realtime add table public.pixel;
  end if;
end;
$$;

insert into public.canvas (name) values ('Canvas 1');

commit;
